coverage:
  range: "40...90"
  round: down
  precision: 2
  
  status:
    project: yes
    patch: no
    changes: no

ignore:
  - ".github/.*"
  - ".vscode/.*"
  - ".setup/.*"
  - ".production/.*"
  - "src/test/.*"
  - "src/main/webapp/.*"
  - "src/main/java/com/rebuild/web/.*"
