commit_message: '[Crowdin] Update translations'
files:
  - source: '/src/main/resources/i18n/language.zh_CN.json'
    translation: '/src/main/resources/i18n/language.%locale%.json'
    languages_mapping:
      locale:
        'zh_CN': 'zh-CN'
        'zh_TW': 'zh-TW'
        'en': 'en-US'
        'ja': 'ja-JP'
